[[Accounts]]
Name = 'la'
Server = 'https://social.lol'
ClientID = 'aE2GieLUH-mygrD3JO0y7sXdx602I5b7ltwJhKpKe-M'
ClientSecret = '72iR_AC5HI3wKxbfXe5_n8LauYVDqHkBFXq5410Z3nc'
AccessToken = '1R39WTq9HJzrBLB_oJgNcaGGSZfqEsGR89elgYWdYks'
